### ISSUE TITLE
file_attachment_steps.rb should be removed from Spreewald

### ISSUE THREAD

**Issue by triskweline** [makandra/spreewald#106]
In `file_attachment_steps.rb` Spreewald has a step that manipulates records in the database:

```
Given the file "image.png" was attached as Image/file to the company above
```

I feel that this step does not belong into Spreewald and should be removed. Spreewald steps should focus on interacting with the screen and observing user behavior. Steps that manipulate ActiveRecord models should be placed in gems like [CucumberFactory](https://github.com/makandra/cucumber_factory), or be left to custom step definitions.

**Comment by judithroth** [comment]
I agree - spreewald steps should not manipulate the database. 
To give users a nicer experience with our gem I would suggest to first add a deprecation warning to the step and to remove it from the README. After some time we can then remove it from the gem.
