### ISSUE TITLE
Strip inlined styles from HTML mail body

### ISSUE THREAD

**Issue by foobear** [makandra/spreewald#109]
Premailer allows inlining styles from a stylesheet into HTML e-mails automatically. When inspecting such e-mails with Spreewald, we can't check for `<p>Hello</p>` because the actual HTML is something like `<p style="margin: 0 0 10px">Hello</<p>`.

Nobody wants to put that into their tests, so we could just automagically `gsub(/ style=".+?"/, '')` from the HTML body, allowing for `<p>Hello</p>` to be expected. Maybe Spreewald's `MailFinder` should always do that or have an option to do so that is enabled by default.

**Comment by judithroth** [comment]
Because of #52 we already decided to implement a step or an option for comparing against stripped text (stripping all tags). When testing webpages, we usually do not test the HTML so I would prefer to not start doing this in emails.

**Comment by foobear** [comment]
Valid point. I'd like my test to expect the e-mail being HTML-formatted, so maybe the step could reflect hat.

**Comment by foobear** [comment]
Closing in favor of #111
