### ISSUE TITLE
Mail steps: prefer HTML body over plain-text body

### ISSUE THREAD

**Issue by foobear** [makandra/spreewald#111]
For multipart e-mails with both an HTML and a plain-text body, `MailFinder.email_text_body` returns a string that starts with the plain-text body, followed by the HTML body including HTML tags.

Instead, we should be doing this:

1. For multipart e-mails, if there is an HTML part, return its text contents (without tags)
2. For multipart e-mails, if is a text part but no HTML part, return the text part's body
3. Else, just return the text body.

Like this:

```ruby
  def email_text_body(mail)
    if mail.html_part
      dom = Nokogiri::HTML(mail.html_part.body.to_s)
      (dom % 'body').text.gsub(/\n\n/, "\n")
    elsif mail.text_part
      mail.text_part.body.to_s
    else
      mail.body.to_s
    end
  end
```

We should also modify existing steps that check the mail body to allow including an option to explicitly reference HTML or plain-text part, like so:

- `Then an email should have been sent with:` uses preferred part, i.e. HTML if available, plain-text else
- `Then an email (HTML) should have been sent with:` uses HTML part, will not fall back to plain-text part
- `Then an email (plain text) should have been sent with:` uses text part, will not prefer HTML part if available

**Comment by judithroth** [comment]
I like this approach. My preferred way of naming the steps would be
* `Then an email should have been sent with:`
* `Then a HTML email should have been sent with:`
* `Then a plain text email should have been sent with:`
to make it sound more natural.

**Comment by foobear** [comment]
Closing issue as we'll implement it as part of #132.
