### ISSUE TITLE
Add current Ruby and Rail to test matrix

### ISSUE THREAD

**Issue by foobear** [makandra/spreewald#120]
Currently, the latest Ruby being tested is 2.4.5, and Rails 4.2. Especially the Rails version is outdated.

We should include Rails 6 (and maybe Rails 5, not sure if it's worth the effort) and a recent Ruby version (2.7.0 at time of writing).
Note that Ruby 2.7 may raise deprecation warnings for syntax changes coming in Ruby 3.

**Comment by judithroth** [comment]
We now have a test project for Rails 6. I don't think having Rails 5 is worth the effort (only mail steps are really making a difference between the rails versions and as far as I know there are no big differences between Rails 5 and Rails 6). As Ruby 2.7.1 had _a lot_ of deprecation warnings I used Ruby 2.6.6. Maybe we could check in about half a year if newer Rails 6 and newer Ruby 2.7 throw fewer deprecation warnings. Switching to Ruby 2.7 for the Rails 6 test project is easy.
