### ISSUE TITLE
Support aria labels

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#122]
What do you think about adding an aria label support to all appropriated steps?

Example:

```
<button aria-label="Close">X</button>
```

```
And I press "Close"
```

**Comment by triskweline** [comment]
This would be a great change!

I just discovered that Capybara [added support for aria-label](https://github.com/teamcapybara/capybara/issues/1528) for fields, links and button a while back. You need to enable it with `Capybara.enable_aria_label = true`.

Capybara API docs [here](https://www.rubydoc.info/github/jnicklas/capybara/Capybara.configure).

**Comment by makmic** [comment]
We observed that the global configuration of Capybara has some major effects on Spreewald. There is already [a paragraph on Capybara](https://github.com/makandra/spreewald#a-note-on-capybara-3) at our README that could be changed into a "recommended Capybara defaults" section.
I vote for adding a recommendation for `enable_aria_label = true`.
