### ISSUE TITLE
Update the selector.rb and a paths.rb examples

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#123]
What do you think about updating the examples of both files `selector.rb` and `paths.rb`?
What do you thin about a task `spreewald initialize` that adds these files to a project and is in the `README.md`? 

For the `selector.rb` template: It should include matchers for BEM and aria labels (we already have this in newer projects).
For the `paths.rb` template: It should allow to handle different routes and support namespaces (we already have this in newer projects).

**Comment by triskweline** [comment]
What do you mean with "it should allow to handle different routes"?

In general I agree with all of these changes because we use them in dozens of projects.

Note that the BEM syntax used by makandra (`block--element` and `-modifier`) is different from [what the rest of the world uses](https://en.bem.info/methodology/naming-convention/), but I think it's OK to be self-serving here.

**Comment by denzelem** [comment]
> What do you mean with "it should allow to handle different routes"?

I mean mappings to routes like this:

```
And I go to the new project page
And I should be on the project page
And I go the form for the project above
And I should be on the list of projects
```

**Comment by codener** [comment]
I would really appreciate reworking paths.rb and selectors.rb. I would like them to contain (pseudo-code):

```
# selectors.rb
<recurse once> containing "...", e.g. the thing containing "foobar"
<BEM> matcher, e.g. the block's element that's modifier
"<literal css>", e.g. "tr:nth-child(3):active"
```

```
# paths.rb
the homepage
the <model name> above
the form for the <model name> above
the path "<literal url>"
```

**Comment by triskweline** [comment]
> "<literal css>", e.g. "tr:nth-child(3):active"

I think we shouldn't encourage users to use CSS selectors in their features.

**Comment by codener** [comment]
@triskweline that's right. However, it is [an exisiting feature](https://github.com/makandra/spreewald/blob/0ec197c4cb87c2c9a0edef3135370b751280421f/lib/spreewald_support/path_selector_fallbacks.rb#L7) of Spreewald and I believe it is good to have this possible.

I'm sorry I didn't read the OP well. I thought we were talking about the paths and selectors fallback configuration: https://github.com/makandra/spreewald/blob/0ec197c4cb87c2c9a0edef3135370b751280421f/lib/spreewald_support/path_selector_fallbacks.rb#L4-L28 This is where I wanted to place my suggestions. With this file already in place, I do not think we need neither an initializer/generator nor example files.

We should, however, describe paths.rb and selectors.rb in the README. Users should know the fallback behavior and how they can add more entries.

---

Btw I have working code for all my suggested entries to paths.rb and selectors.rb.

**Comment by triskweline** [comment]
> However, it is an exisiting feature of Spreewald and I believe it is good to have this possible.

We're planning to deprecate a lot of functionality in 2.99 und remove it in 3.0.

**Comment by codener** [comment]
We should also inform users that `within` calls can be chained to target nested elements. Examples:

```
Then I should see "Überschrift" within the item within the promoted row
```

**Comment by judithroth** [comment]
Done with cb71537a and a952ed8d
