### ISSUE TITLE
Add flash steps

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#125]
What do you think about adding steps for flashes? 

```
And I dismiss all flashes
And I dismiss the "..." flash
And I should not see a flash message
And I should see a flash message "..."
And I should( not)? see an? ... flash "..."
And I should( not)? see an? ... flash
```

**Comment by triskweline** [comment]
I think the HTML markup for flash messages (and their variants: notice, warning, success, failure, error, ...) is different in every app.

**Comment by judithroth** [comment]
We clearly decided against this, so I'm closing this issue.
