### ISSUE TITLE
Add icon button steps

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#127]
What do you think about adding steps for icon buttons?

```
And I click the "..." icon button
And I should( not)? see an? "..." icon
```

**Comment by judithroth** [comment]
I think this step would be to specific to add to spreewald, because it depends too much on how you implement your icon buttons. Also, you can already cover this use case very easily with the `I click on the element for .*?` step and a good definition of the icon selectors in `selectors.rb`.

**Comment by triskweline** [comment]
Icons work differently in every app, so it should not be in Spreewald.

I don't know what `And I click the "..." icon button` would do, but if it is about pressing a button with no textual label, it should have an `[aria-label]` and `When I click on` (or the default selectors.rb) should recognize that. See #122, #123.

**Comment by judithroth** [comment]
We clearly decided against this, so I'm closing this issue. Thanks for voting :)
