### ISSUE TITLE
Add step to navigate between fields

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#129]
What do you thin about adding the following step?

```
And I press (return|tab|.) in the focused field
```

**Comment by judithroth** [comment]
I never needed this in a project. So I think this is too specific for spreewald.

**Comment by codener** [comment]
This very step might be too specific, but some form of key pressing support would be nice. We're doing this quite a few times: arrow keys in a lightbox, chat submit, search-as-you-type etc.

What about a `When I press the <name> key` step that looks the key up from a named, extensible table? This way it would be easy to press e.g. arrow keys, enter, or escape, and users can add their own keys and combinations, like `Ctrl+Enter`.

That step should support the `within` extension, which would allow to express your suggested step with even more flexibility: `And I press the return key within the focused field`.

Adding this step would encourage adding more keyboard support to applications, which is a good thing IMHO.

**Comment by makmic** [comment]
I'm not sure if it belongs to Spreewald or not.
One remark to @codener's step: I would say that the `within` keyword does not suite this step very well. It usually means "some element within the specified parent node" in Spreewald.. how about a new keyword that means "exactly this element"? Like:

`And I press the return key on the focused field`.

(I know `on` is too generic for the underlying RegEx, just an example.)

**Comment by foobear** [comment]
We've decided that this is too specific to be kept in Spreewald.

Most often, this is probably testing component behavior and a Jasmine spec would have been a better approach then writing an integration test using Cucumber.

**Comment by codener** [comment]
Agreed that putting single letters into text fields feels like unit testing.

What about the use case of **keyboard shortcuts**? E.g. Ctrl + S => Save, Esc => Close dialog, Arrow keys => Navigate, and more custom Keys? I know we have special Cucumber steps in a few projects that enable this. "Keyboard shortcuts" are generic enough for such a step to become a part of Spreewald, and again, it would encourage adding keyboard support to applications (which is a bit lacking IMHO).

**Comment by foobear** [comment]
All of those examples could be tested by speccing the corresponding component (form, dialog, slider) using Jasmine tests and I'd dare to say you are better off doing it that way.

If you still want to test complex behavior in a Cucumber test, pressing a key is a simple Capybara call that you can call on the element you want to call it on.
Pressing keys in focused fields is a behavior too specific for Spreewald to cover.
