### ISSUE TITLE
Update fields with error step

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#131]
We override the following steps in all projects that are using Bootstrap.

```
And the "..." field should( not)? have an error
```

What do you think about updating the step?

**Comment by judithroth** [comment]
I always wanted to update this step to use bootstrap. But we should try to not add dependencies to other libraries and their exact versions, because this will again be out of date soon. 
Maybe we should remove this step from spreewald instead, so that every project can implement the step the way it fits for the project (as it is already done through overriding).

**Comment by triskweline** [comment]
Don't you have a wrapping `<div class="field_with_errors">...</div>` when using Bootstrap?

**Comment by codener** [comment]
I have multiple projects that use Bootstrap 3 but do not override the "should have an error" step. What makes the extended step necessary? Is it a special Bootstrap configuration? Or is it Bootstrap 4?

**Comment by judithroth** [comment]
You're right, @codener. This seems to be an edge-case. In my project the spreewald step works fine, except for an file upload field:
```
    .panel-body
      = form.file_field :csv_file
```
This is part of a `bootstrap_form` form.
It results in the following HTML:

```
<div class='panel-body'>
  <div class="form-group has-error">
    <label class="control-label required" for="partner_user_group_import_csv_file">CSV-Datei muss ausgefüllt werden</label>
    <input type="file" name="partner_user_group_import[csv_file]" id="partner_user_group_import_csv_file" />
  </div>
</div>
 ```
The Spreewald step only checks for a `field_with_errors`. I am not sure why this is missing in the project, could be some kind of misconfiguration.

**Comment by foobear** [comment]
Projects may reconfigure this behavior and many of our recent projects don't use `field_with_errors` at all but style their Bootstrap 4 inputs by adding just Bootstrap's classes.

This is not tied to Bootstrap 4 and implemented on a per-project basis, so Spreewald can't cover all approaches.

We'll keep the step as is. If you don't want to overwrite the step in your project, you need to provide a `field_with_errors` container. If you don't want to do that, simply overwrite the step.
