### ISSUE TITLE
Split steps in more bundles

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#133]
Maybe we could split the steps in more bundles, so we have less conflicts in bigger projects? This is a more general approach, when more steps are added that can be combined to a group. E.g. tab steps become an own bundle, that can be required.

**Comment by triskweline** [comment]
Having more or fewer files does not make a difference for me. All Spreewald steps are `.overridable` so there can never be a conflict with app-specific steps.

Note that when you publish the filenames of these bundles they become part of our public API and we cannot rename files or move step definitions without breaking client apps.

**Comment by judithroth** [comment]
We clearly decided against this, so I'm closing this issue. Thank your for the suggestion and for voting :)
