### ISSUE TITLE
Remove `/^I should get a text response$/ ` which is only an alias

### ISSUE THREAD

**Issue by judithroth** [makandra/spreewald#135]
The step just calls the `I should get a response with content-type "text/plain"` step. 
I would prefer not to have many aliases in Spreewald. Of course if there is a very complex step that most of the time needs to be used in one simple way an alias may make sense, but this one is very simple.

:+1: to vote for deprecating and removing this step
:-1: to vote for keeping

**Comment by triskweline** [comment]
Can you even see the content-type in a Selenium test?

**Comment by judithroth** [comment]
To avoid unnecessary version bumps (and confusion) we should approach all "remove xy" issues at once. Also, before removing, we want to release a version x.99 which prints deprecation warnings for everything that is removed in version x+1.
