### ISSUE TITLE
Remove `/^I wait for the page to load$/`

### ISSUE THREAD

**Issue by judithroth** [makandra/spreewald#136]
Using steps like this is a bad pattern. It would be better to check the page for the expected result (e.g. check that something is now visible) ([see this](https://makandracards.com/makandra/12139-waiting-for-page-loads-and-ajax-requests-to-finish-with-capybara)). We should try not to encourage bad patterns.
The step also relies on jQuery, which is unexpected and could fail.

:+1: vote for removing
:-1: vote for keeping

**Comment by makmic** [comment]
I clearly agree that this step should be avoided whenever possible. Nevertheless it will complicate the update to Spreewald 3 for many of our projects. Maybe they just have to copy and adjust the step for their need (e.g. w/o jQuery).

**Comment by judithroth** [comment]
To avoid unnecessary version bumps (and confusion) we should approach all "remove xy" issues at once. Also, before removing, we want to release a version x.99 which prints deprecation warnings for everything that is removed in version x+1.
