### ISSUE TITLE
Modernize time steps

### ISSUE THREAD

**Issue by judithroth** [makandra/spreewald#137]
The time steps in Spreewald rely on the Timecop gem.
Since 4.1 Active Support has its own time travel functionality, that seems to cover all the usecases that Spreewald offers (`travel`, `travel_to`, `freeze_time`. Since almost all our projects already include Active Support we should switch to that. 

:+1: for switching to Active Support
:-1: for keeping Timecop

**Comment by triskweline** [comment]
We still have a few projects in active development that are on Rails 3.2 LTS. You cannot upgrade ActiveSupport without upgrading Rails. Because of this it's a :-1: from me.

**Comment by foobear** [comment]
We've discussed this and will implement as follows:

- When Timecop is available, we will use Timecop
- When Timecop is unavailable, but ActiveSupport time helpers are available, we will use them
- If neither is available, time steps will be undefined. This is similar to the current behavior where steps are undefined when Timecop is unavailable.
