### ISSUE TITLE
Wrong documentation about developer tags @slow and @single

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#138]
The README says `@slow` instead of `@slow-motion` and `@single` instead of `@single-step`.

https://github.com/makandra/spreewald/blame/f9106ca5538078efef5e365aa64f055f14c05429/README.md#L149-L156

https://github.com/makandra/spreewald/blob/f9106ca5538078efef5e365aa64f055f14c05429/lib/spreewald/development_steps.rb#L55-L64

**Comment by judithroth** [comment]
Thanks for the report, we will fix the README :)

**Comment by makmic** [comment]
Thanks! That was actually a small bug for the code that is generating the README. Fixed
