### ISSUE TITLE
"an email should have been sent with" step behaves incorrectly when not specifying headers

### ISSUE THREAD

**Issue by foobear** [makandra/spreewald#157]
The `an email should have been sent with:` step always considers everything until the first `\n\n` to be headers. It ignores any lines that do not match the header style, so when given only a message body, it ignores anything until the first `\n\n`.

Example:

```
Then an email should have been sent with:
  """
  Hello
  
  Bye
  """
```

This passes for an email where the body is only `"Bye"`.

I suggest raising an error when encountering an invalid header line, or considering the entire string as the message body, if the headers section does not contain header-link lines.

**Comment by FLeinzi** [comment]
I made a pull request for this issue: https://github.com/makandra/spreewald/pull/158

We will now interpret all lines as body when not specifying headers.
