### ISSUE TITLE
Rework "field should have the error" and "field should( not)? have an error " steps

### ISSUE THREAD

**Issue by judithroth** [makandra/spreewald#164]
We're overwriting these steps in many of our projects, because they use Bootstrap.
I think it's time to rework these steps so that they work out of the box with plain Ruby on Rails and with bootstrap (how we use it). 

It would also be possible to add a config option, e.g. `Spreewald.field_error_class = 'custom-error'`. This way we would avoid a "dependency" to bootstrap if anyone thinks this is a problem.

**Comment by begerdom** [comment]
Implemented in bdf556741f694aed5eaf9d43655989e24cd28594 and f726e724a107e0ad44ef080c207f70f95126d246
