### ISSUE TITLE
Installation instructions are confusing to newcomers

### ISSUE THREAD

**Issue by triskweline** [makandra/spreewald#188]
I work with a lot of people who install Spreewald for the first time, and they are often confused by the installation instructions in the README.

I recommend the following changes:

1. The "Usage" section where we `require` the step files should be merged with "Installation".
2. Installation should recommend creating a `paths.rb` and `selectors.rb` and link to templates. There is no mention of these files anywhere in the README.

**Comment by judithroth** [comment]
I hope it's better now :)
