### ISSUE TITLE
Support for Ruby 3 for step `/^(.*) within (.*[^:])$/`

### ISSUE THREAD

**Issue by brunosedler** [makandra/spreewald#192]
Within the step  `/^(.*) within (.*[^:])$/ ` the selector is allowed to be an array. That is the case when we want to pass options with selectors for example `'[.foo', text: 'bar']`. 

With the [separation of positional and keyword arguments in Ruby 3.0](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) this code will break, as a hash will be passed to `have_selector` and to `within`.
In Ruby 2.7 I get the following deprecation warnings caused by this step.
```
/persistent/bundle-2.7.6/ruby/2.7.0/gems/capybara-3.37.1/lib/capybara/rspec/matchers.rb:19: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/persistent/bundle-2.7.6/ruby/2.7.0/gems/capybara-3.37.1/lib/capybara/rspec/matchers/have_selector.rb:9: warning: The called method `initialize' is defined here
/persistent/bundle-2.7.6/ruby/2.7.0/gems/capybara-3.37.1/lib/capybara/dsl.rb:52: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/persistent/bundle-2.7.6/ruby/2.7.0/gems/capybara-3.37.1/lib/capybara/session.rb:359: warning: The called method `within' is defined here
```

I was able to fix the problem locally by overwriting the step and the `with_scope` helper method with the following:
```
When /^(.*) within (.*[^:])$/ do |nested_step, parent|
  selector = _selector_for(parent)
  if selector.is_a?(String)
    expect(page).to have_selector(selector)
  elsif selector.is_a?(Array)
    html_class, options = deconstruct_selector(selector)
    expect(page).to have_selector(html_class, **options)
  else
    # could also be a Capybara::Node::Element
  end
  patiently do
    with_scope(parent) { step(nested_step) }
  end
end

module WithinHelpers
  def with_scope(locator)
    if locator
      selector = _selector_for(locator)
      if selector.is_a?(Array)
        html_class, options = deconstruct_selector(selector)
        within(html_class, **options) { yield }
      else # String or Capybara::Node::Element
        within(selector) { yield }
      end
    else
      yield
    end
  end

  def deconstruct_selector(selector)
    html_class, *options_array = selector
    options = options_array.reduce({}, :merge)
    [html_class, options]
  end
end
```

This worked for me, and especially the the `have_selector` part should be alright, since `have_selector` expects to [receive only one positional argument followed by keyword args](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rspec/matchers/have_selector.rb#L11) but the `within`-part might not work for all cases, as `within` also allows something like `within(:xpath, '//header')`

**Comment by FLeinzi** [comment]
This was fixed in https://github.com/makandra/spreewald/pull/194 and has been released as Spreewald 4.4.1
