### ISSUE TITLE
Ruby 3.0 support for `When /^(?:|I )attach the file "([^"]*)" to "([^"]*)"$/`

### ISSUE THREAD

**Issue by niklas-hasselmeyer** [makandra/spreewald#200]
The step `When /^(?:|I )attach the file "([^"]*)" to "([^"]*)"$/` (web_steps.rb:163) doesn't work with Ruby 3.0.

The step uses
```
attach_file(field, File.expand_path(path), options)
```
However, [that method's definition](https://github.com/teamcapybara/capybara/blob/69abf9e24cc225aca1ef7e25b1bfb7b61017f017/lib/capybara/node/actions.rb#L279) is
```
def attach_file(locator = nil, paths, make_visible: nil, **options)
```
so the step should call `attach_file(field, File.expand_path(path), **options)` instead.

**Comment by FLeinzi** [comment]
This is fixed in `4.4.4`.
