### ISSUE TITLE
patiently retries to few times when Capybara uses its own retry feature

### ISSUE THREAD

**Issue by niklas-hasselmeyer** [makandra/spreewald#202]
The current state of using both Spreewald's `patiently` and Capybara's [automatic retry feature](https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends) is flawed, as unlucky timing can easily make tests flaky.

Example: The `Then  /^the "([^"]*)" field should( not)? contain "([^"]*)"$/` step (code [here](https://github.com/makandra/spreewald/blob/e537468e0a56efc5311dedd4bedf34d5cd0d69cc/lib/spreewald/web_steps.rb#L317)).
When the field with the given label is replaced by javascript, this can happen:

1. The step runs, sees the old field with the old value, expectation fails, Spreewald's patiently retries
2. Line 319 runs, assigning the old field to the `field` variable.
3. Javascript replaces the field
4. Lines 321-331 run and try to get the value of the old field. Selenium throws a StaleReferenceError and Capybara's retry feature kicks in.
5. For the next `default_wait_time` seconds, Capybara tries getting the value of the old field.
6. The time expires, Capybara throws the StaleReferenceError.
7. `patiently` won't retry because the `default_wait_time` has already expired and the one guaranteed retry was already used in step 1.

I think the best way to deal with this issue would be to lower Capybara's default wait time inside a Spreewald patiently block, so that Spreewald can still retry under these circumstances.

**Comment by kratob** [comment]
This sound totally reasonable.

Then again, there is https://github.com/makandra/spreewald/commit/d8b9619117fde7a634a268f92908dcd2d46517cb, which specifically *reverts* the exact change you're proposing.

I cannot remember why we had to revert it. I assume it must have something to do with nested patiently blocks, but can't put my finger on it.

Maybe a safeish way would be to change the mechanism to always allow "one more try" after time is up (instead of guaranteeing 2 tries in total)? Of course that might result in slower failures.

**Comment by kratob** [comment]
Or, alternatively, we could change it so that
- patiently records the time when the block *started*
- patiently will retry as long as that timestamp is before the default_wait_time
@niklas-hasselmeyer do you agree that this would solve your usecase?

**Comment by niklas-hasselmeyer** [comment]
I can imagine that the reason behind [d8b9619](https://github.com/makandra/spreewald/commit/d8b9619117fde7a634a268f92908dcd2d46517cb) was to allow Capybara's own retry feature, which can speed up tests.

When I wrote the issue, I thought that the best fix was to make the two timeouts (Spreewald's and Capybara's) independent. Both of your suggestions sound reasonable, too, and would solve my issue.

**Comment by kratob** [comment]
Fix is released as version 4.5.0.
