### ISSUE TITLE
@javascript steps are not tested

### ISSUE THREAD

**Issue by codener** [makandra/spreewald#28]
Currently, we cannot test steps that are designed for @javascript scenarios. Creating a consistent environment for making them pass is far too expensive.

One day we might try using phantomJS or RSpec.

**Comment by judithroth** [comment]
Fixed with commit 2a04dc7796ca5760f4dc6973a27d988e248d24a6 (integration of selenium in test applications).

**Comment by codener** [comment]
Wow, you really made it? I didn't think it was possible ...
