### ISSUE TITLE
`Then "text" should be visible` step broken for `ßäöü`

### ISSUE THREAD

**Issue by martin-straub** [makandra/spreewald#39]
Since commit https://github.com/makandra/spreewald/commit/3dbdc89ec18a85ad9f05781acb642f303310476f
the step doesn't see German special characters.

**Comment by judithroth** [comment]
Fixed with commit d5ee340b45191d5f9e2b43b7db6d018a518e7cfe.

**Comment by codener** [comment]
Thank you!
