### ISSUE TITLE
Ambiguous step definitions

### ISSUE THREAD

**Issue by codener** [makandra/spreewald#41]
The "within" step collides with the "checkbox should be checked" step.

#### Error message:

    Ambiguous match of "the "Project A" checkbox within '.projects' should be checked":
      
    spreewald-1.1.1/lib/spreewald/web_steps.rb:40:in `/^(.*) within (.*[^:])$/'
    spreewald-1.1.1/lib/spreewald/web_steps.rb:267:in `/^the "([^"]*)" checkbox(?: within (.*))? should be checked$/'

#### Suggested solutions:
- a) remove "within" support from the checkbox step, as the within steps takes care of this
- b) for better wording, find a way to turn of the within step for the checkbox step

**Comment by henning-koch** [comment]
Let's do a) (and accept that it breaks a few scenarios).
