### ISSUE TITLE
Missing rspec dependency

### ISSUE THREAD

**Issue by triskweline** [makandra/spreewald#50]
Although Spreewald requires `rspec`, it doesn't state so in its gemspec.
It should also `require "rspec"` when its being loaded.

This is usually not an issue because something, somewhere has already loaded RSpec before Spreewald, but I tripped over it tonight.

**Comment by p886** [comment]
Also, the `Then show me page` step requires the `launchy` gem. It may be a good idea to add `launchy` as a runtime dependency, even though that seems to be the only step requiring this gem and it is mentioned in the README.

**Comment by codener** [comment]
I believe it suffices to let Spreewald depend on `rspec-expectations`. However, I am not sure about the backwards compatibility of this.

**Comment by judithroth** [comment]
This was implemented with 8f4dcc7c5f24a7660bf9e6fda8959a2631ad8bc2
