### ISSUE TITLE
Make "an email should have been sent with:" step more flexible

### ISSUE THREAD

**Issue by codener** [makandra/spreewald#52]
Today the mentioned step bit me when I had too much white space:

``` gherkin
Then an email should have been sent with:
  """
  From: < 2+ spaces here > system@example.com
  """
```

The step should be flexible enough to strip any white space around email addresses and/or the subject.

---

Also, it would be nice to have better output if the specified email could not be found. Current output is `expected nil.present? to return true, got false`. Improved output:

```
Could not find email with:
<multiline string>

Found emails:
<list of emails like "show me the emails" prints them>
```

**Comment by denzelem** [comment]
Some notes here:
- `an email should have been sent with`: Pretty awesome would be a finder, that either says no email at all or showing the diff to the best matching email
- Using `an email should have been sent with:` and `that mail should have the following lines in the body:` will help to find errors in the body easier, but:
  - If there are two email where only the body differs, the diff might be misleading as you see the wrong email
  - Maybe combining these steps with its features would be nice

**Comment by codener** [comment]
Could you please look into this? The `expected nil.present? to return true, got false` thing is an issue whenever the expected email does not match.

What do you think about my suggested output? It should be quite easy to enhance that step.

**Comment by denzelem** [comment]
Can we prioritize this issue?

In general it always feels a little bit exhausting to use the spreewald mail steps. Here are some points that come to my mind first:

1. If the mail condition does not match any existing mail, the error should return all sent mails (this issue) and if possible a diff.
2. HTML mails should be comparable against a plain text.
3. I often forget about a step to test just the `subject` and/or `to`; it seems to exists but is not documented. Usually I use e.g. `spreewald subject` within a project, which does not return any result.
4. I often don't know if a text must match exactly or is allowed to be a substring (e.g. subject, body)
5. The use of a special order to get steps working. 

Maybe we can try to collect current issues with the spreewald mail steps and try to fix them.

**Comment by makmic** [comment]
Hi @denzelem,
I'll have a look at these enhancements during the next week/s.

Could you clarify point 5. of your list? I'm not sure in which context there should be a special order.

**Comment by denzelem** [comment]
With point 5 I mean all the steps that include the hint:

```
Only works after you've retrieved the email using "Then an email should have been sent with:"
```

**Comment by denzelem** [comment]
I summarized this issue in #132.
