### ISSUE TITLE
Time travel steps should accept a time zone identifier

### ISSUE THREAD

**Issue by triskweline** [makandra/spreewald#54]
I should be able to say:

```
Given the time is 2015-05-01 PDT
```

Time zone identifiers should be 3 or more uppercase letters like PDT, CET, CEST, JST, etc.

**Comment by henning-koch** [comment]
Apparently `Time.zone.parse` doesn't recognize CET and CEST as identifiers. It does recognize PDT, PST, EDT, EST.

**Comment by henning-koch** [comment]
OK, this seems to be a limitation of Rails 2. It works in Rails 3+.

**Comment by foobear** [comment]
Closing this since both `Time.parse` and `Time.zone.parse` work on Rails 3+ as they should:

```
>> Time.parse('2015-01-01 08:00 PST')
=> 2015-01-01 08:00:00 -0800
>> Time.parse('2015-01-01 08:00 +05:30')
=> 2015-01-01 08:00:00 +0530
```

```
>> Time.zone.parse('2015-01-01 08:00 PST')
=> Thu, 01 Jan 2015 16:00:00 UTC +00:00
>> Time.zone.parse('2015-01-01 08:00 +05:30')
=> Thu, 01 Jan 2015 02:30:00 UTC +00:00
```
