### ISSUE TITLE
New step for inspecting PDF attachments

### ISSUE THREAD

**Issue by codener** [makandra/spreewald#55]
These steps allows for inspection of PDF documents attached to sent emails.

```
# For email attachments
When /^I inspect the attached PDF$/ do
  expect( ActionMailer::Base.deliveries ).to_not be_empty

  # @mail can be set by one of the other email steps
  @mail ||= ActionMailer::Base.deliveries.last
  attachment = @mail.attachments.first{ |a| a.mime_type == 'application/pdf' }
  expect( attachment ).to be_present, 'Could not find an attached PDF'

  pdf = StringIO.new(attachment.decoded)
  reader = PDF::Reader.new(pdf)

  @pdf = reader.pages.collect(&:text).join("\n")
end

Then /^I should( not)? see "(.+?)" in the PDF$/ do |negate, text|
  to = negate ? :to_not : :to
  expect( @pdf ).send to, include(text)
end

```

Note that this requires the `pdf-reader` gem in the `:test` group of your Gemfile.

**Comment by henning-koch** [comment]
I like having such a step.

I wouldn't make pdf-reader a dependency of the gem. Projects should opt-in manually.

We should also probably rewrite to `should` syntax so it works with older RSpecs.

**Comment by foobear** [comment]
Inspecting PDF attachments of e-mails is an edge case that should be covered per project. I don't see us adding this step to spreewald any time soon.
