### ISSUE TITLE
Encoding error when testing emails with attachments

### ISSUE THREAD

**Issue by alietz** [makandra/spreewald#56]
Since spreewald 1.2.8 (on Rails 4.2 / Ruby 2.1.5), the step "an email should have been sent with" fails with 
`incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)`
The error seems to happen on line 59 of `mail_finder.rb`:
`mail_bodies.join('\n')`
If I test an email with a PDF attached, the mail body's encoding is UTF-8, but the PDF's encoding is ASCII-8BIT, so the join throws an error.
Would it make more sense not to test attachments at all? Or let the developer whether to test them?

**Comment by henning-koch** [comment]
@martin-straub Is @alitz' issue fixed with [01947fc](https://github.com/makandra/spreewald/commit/01947fc36db244ebb9dd7638860d35cbf64b452b)?

**Comment by alietz** [comment]
Yes, the issue is solved with spreewald 1.2.12. Thanks!

**Comment by alietz** [comment]
Yes, the issue is solved with spreewald 1.2.12. Thanks!
