### ISSUE TITLE
Not able to install Spreewald

### ISSUE THREAD

**Issue by lokki007** [makandra/spreewald#62]
When I'm running `gem install spreewald` I got an error: 
`installing into parent path /Users/idikhtiar/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/shared/app of /Users/idikhtiar/.rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/spreewald-1.5.3 is not allowed`

My work-around was: 
1. running `gem update --system`
2.  `gem install spreewald`
3. deleting spreewald folder from gems folder
4. `gem install spreewald`

Could reproduce this on another machine with the same issue. Not pushing this code to Staging tests because it will fail on Jenkins. Any idea if it's possible to fix?

**Comment by judithroth** [comment]
This is a bug in rubygems 2.5.1. It is fixed in newer versions, so `gem update --system` as suggested by lokki007 solves this problem.
