### ISSUE TITLE
spreewald independet from testframework (use with minitest)

### ISSUE THREAD

**Issue by matzke** [makandra/spreewald#67]
I use cucumber w capybara and minitest (rails default). The original web_steps.rb supported both rspec and minites like this ...

```cucumber
Then /^(?:|I )should see "([^"]*)"$/ do |text|
  if page.respond_to? :should
    page.should have_content(text)
  else
    assert page.has_content?(text)
  end
end
```

it would be nice if spreewald would support more than just rspec - related to #50.

**Comment by matzke** [comment]
@henning-koch "Projects should opt-in" rspec / minitest, too - see https://github.com/makandra/spreewald/issues/55#issuecomment-127138538

**Comment by henning-koch** [comment]
Unfortunately we're using RSpec exclusively in our team. We're not ready to maintain a second test framework. Sorry!
