### ISSUE TITLE
New step for visible button

### ISSUE THREAD

**Issue by matzke** [makandra/spreewald#69]
check if page has a button ...

```cucumber

Then /^(?:|I )should see a "([^"]*)" button$/ do |text|
  if page.respond_to? :should
    page.should have_button(text)
  else
    assert page.has_button?(text)
  end
end
```

**Comment by codener** [comment]
Nowadays a "button" is hard to define, as we're mostly styling links to _look_ like buttons, or even styling buttons to look like links.

I'm afraid this step sounds much more generic than it actually is or possibly could be, hence I hesitate to add it to Spreewald. I would suggest to simply add this step to a project's local step definitions.
