### ISSUE TITLE
Spreewald should never check the current driver name, but its class

### ISSUE THREAD

**Issue by codener** [makandra/spreewald#74]
In multiple places in web_steps.rb, spreewald distinguishes Capybara drivers by their name. However, since the driver name is variable (i.e. it is chosen by project developers), this is a weak means for differentiation.

Spreewald should check the driver's class instead, e.g. check if it is `Capybara::Selenium::Driver` or the like.

**Comment by triskweline** [comment]
Note that there are many JavaScript capable drivers that are not using Selenium. E.g. `capybara-webkit`, `poltergeist`, headless chrome in the near future.

**Comment by foobear** [comment]
@codener I'm not sure I understand how checking against `Capybara::Selenium::Driver` is better than checking against `:selenium`. Class names are more subject to change than an identifier like `:selenium`, IMHO.

**Comment by triskweline** [comment]
Neither solution has ever broke down in us in 10 years or so? Maybe just decide on one and expose with via `Spreewald.javascript_scenario?` so people can override it if needed.

**Comment by foobear** [comment]
Today I worked with multiple Chrome sessions because of device emulation. `Capybara.current_driver == :selenium` will only work for exactly one driver that is named like that.

I vote for using `Capybara.current_session.driver.is_a?(Capybara::Selenium::Driver)` instead.
We should still place it inside a method that can be overwritten if needed.

**Comment by triskweline** [comment]
Is this always right?

```
Before '@javascript' do
  @javascript_scenario = true
end
```

**Comment by foobear** [comment]
Not really. For example, we used `@mobile` in a project recently which implied using Selenium because of mobile emulation, not because it supports JavaScript.

Would still favor checking inheritance.

**Comment by codener** [comment]
Today, I could not use the `I switch to the new tab` step, because it requires the current driver to be called `:selenium`. However, my project features multiple Javascript-capable drivers, and the driver for that very test was not named `:selenium`. 

Would be awesome if we could fix Spreewald any time soon.

**Comment by triskweline** [comment]
> Maybe just decide on one and expose with via Spreewald.javascript_scenario? so people can override it if needed.

This is the one solution we all agreed on.

**Comment by judithroth** [comment]
Done with 1.12.2 / 196b01634710b93c3eaef77c41aca3efbf8dc2e5
