### ISSUE TITLE
Add Selenium::WebDriver::Error::NoSuchAlertError to RETRY_ERRORS

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#75]
Maybe we can add `Selenium::WebDriver::Error::NoSuchAlertError` to `ToleranceForSeleniumSyncIssues::RETRY_ERRORS`.

**Comment by kratob** [comment]
Fine by me.

**Comment by denzelem** [comment]
Done in d5e61f4191ec2ce6de91ab23da67a9922771428d.
