### ISSUE TITLE
Add patiently-disabling step

### ISSUE THREAD

**Issue by codener** [makandra/spreewald#76]
Recently I used this meta step to test things I needed _in that very moment_, and not after a few seconds. It effectively disables `patiently`'s patience for the given step.

Usage: Append ` now` to any step:
```
Then I should see "Hallo Welt" now
```

I think this should be incorporated into Spreewald.

```
# Disable #patiently (run a step with wait-time 0)
# Then I should see "Hallo Welt" now
When /^(.*) now$/ do |step_text|
  begin
    old_wait_time = Capybara.default_max_wait_time
    Capybara.default_max_wait_time = 0

    step step_text
  ensure
    Capybara.default_max_wait_time = old_wait_time
  end
end
```

**Comment by judithroth** [comment]
This seems to be an edge case in my opinion. At least I have not needed something like this yet... I would prefer not to add rarely used steps to spreewald.

**Comment by triskweline** [comment]
@codener Have we used the `... now` in a second project since the video player we wrote? I think this would be a good indication that this is universally useful.

@judithroth The use case for this is tests where the timing matters.

**Comment by codener** [comment]
Yes, I have just copied it over to another project. However, I'm using it in only one place there. 
We may wait and see if it'll further prove helpful.
