### ISSUE TITLE
Email steps do not support CRLF in plain text mails

### ISSUE THREAD

**Issue by denzelem** [makandra/spreewald#83]
https://github.com/mikel/mail/pull/1168
https://github.com/mikel/mail/commit/d17be66765f7f63caa5d5cedb67a597f853a4402

The mail gem switched from `\n` to `\r\n` line breaks (LF to CRLF) in plain text mails (2.7.1). This affects at least the step `Then an email should have been sent with: ...`. You will see a error message like `expected `nil.present?` to return true, got false (RSpec::Expectations::ExpectationNotMetError)`, as the body does not match anymore.

Internally this part `https://github.com/makandra/spreewald/blob/878862fb6b6d0a36cf2f064c395b06926ca32eea/lib/spreewald_support/mail_finder.rb#L46` needs to have a proper support for `\n` and `\r\n`.

```
"test\r\ntest".include?("test\ntest") => false
```

**Comment by foobear** [comment]
I believe Spreewald could just `gsub` all linebreaks as required. I'm using this patch to work around the issue:

```ruby
module SpreewaldMailFinderLinebreaksFix
  def email_text_body(mail)
    super(mail).gsub("\r\n", "\n")
  end
end

MailFinder.singleton_class.prepend(SpreewaldMailFinderLinebreaksFix)
```
